# Build the 10-level pack that ships inside index.html.
#
# The pictures here are mine, drawn as ASCII grids: one character per pixel, a
# legend mapping each character to a palette id, '.' for empty. Nothing is
# derived from another game's level files, so this pack is safe to publish.
#
# The SCHEMA and its invariants are the ones the simulation needs:
#   - SlotCount == ConveyorLimit == 5
#   - per-material ammo == that colour's pixel count, EXACTLY
#   - shooter ammo inside the 10..40 band the original uses (see split)
#   - no feature containers: these are plain pictures
#
# Layering rule that keeps them solvable: a shooter can only hit the SURFACE
# pixel of a scan line, so every colour needs a pixel on the silhouette at the
# start or it sits idle until the colour covering it peels away. peel() below
# strips a picture the way the game does and proves the board empties.
#
# Output: pack/levels.js, inlined by build_mine.py.
import base64
import gzip
import json
import os
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_levels import EMPTY_PIC

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.abspath(os.path.join(HERE, '..', 'pack'))

# ------------------------------------------------------------------ pictures

SPROUT = ("""
...GG......GG...
..GGGG....GGGG..
.GGGGGG..GGGGGG.
..GGGGG..GGGGG..
...GGGG..GGGG...
.....GGSSGG.....
.......SS.......
.......SS.......
.......SS.......
......DDDDDD....
.....DDDDDDDD...
....DDDDDDDDDD..
.....DDDDDDDD...
......DDDDDD....
""", {'G': 12, 'S': 9, 'D': 15})

DROPLET = ("""
........WW........
.......WWWW.......
......WWWWWW......
......WWWWWW......
.....WWWWWWWW.....
....WWWWWWWWWW....
....WWWLLWWWWW....
...WWWWLLWWWWWW...
...WWWWLLWWWWWW...
..WWWWWLLWWWWWWW..
..WWWWWWWWWWWWWW..
..WWWWWWWWWWWWWW..
..MWWWWWWWWWWWWM..
..MMWWWWWWWWWWMM..
...MMMWWWWWWMMM...
....MMMMMMMMMM....
......MMMMMM......
........MM........
""", {'W': 2, 'L': 8, 'M': 6})

STAR = ("""
........YY........
........YY........
.......YYYY.......
.......YYYY.......
......YYYYYY......
OOOOOOYYYYYYOOOOOO
.OOOOYYYYYYYYOOOO.
..OOOYYYYYYYYOOO..
...YYYYYCCYYYYY...
...YYYYYCCYYYYY...
..YYYYYYYYYYYYYY..
..YYYYYYYYYYYYYY..
..YYYYYY..YYYYYY..
.YYYYY......YYYYY.
.OOOO........OOOO.
.OOO..........OOO.
..O............O..
""", {'Y': 8, 'O': 4, 'C': 23})

APPLE = ("""
.........SS.........
.........SS...LLL...
.........SS.LLLLLL..
....RRRRRRRRLLLLL...
..RRRRRRRRRRRRLL....
.RRRRRRRRRRRRRRRR...
.RRRRRRRRRRRRRRRRD..
RRRRRRRRRRRRRRRRRDD.
RRRRRRRRRRRRRRRRRDD.
RRRRRRRRRRRRRRRRRDD.
RRRRRRRRRRRRRRRRRDD.
RRRRRRRRRRRRRRRRRDD.
.RRRRRRRRRRRRRRRDDD.
.RRRRRRRRRRRRRRRDD..
..RRRRRRRRRRRRRDD...
...RRRRRRRRRRRDD....
....RRRRRRRRDD......
......RRRRDD........
""", {'R': 0, 'D': 22, 'L': 16, 'S': 15})

MUSHROOM = ("""
......CCCCCCCC......
....CCCCCCCCCCCC....
...CCSSCCCCCCSSCC...
..CCCSSCCCCCCSSCCC..
..CCCCCCCSSCCCCCCC..
.CCCCCCCCSSCCCCCCCC.
.CCSSCCCCCCCCCCSSCC.
CCCSSCCCCCCCCCCSSCCC
CCCCCCCCCCCCCCCCCCCC
.TTTTTTTTTTTTTTTTTT.
....TTTTTTTTTTTT....
.....TTTTTTTTTT.....
.....TTTTTTTTTT.....
.....TTTTTTTTTT.....
.....TTTTTTTTTT.....
....TTTTTTTTTTTT....
...BBBBBBBBBBBBBB...
..BBBBBBBBBBBBBBBB..
""", {'C': 22, 'S': 8, 'T': 23, 'B': 15})

BALLOON = ("""
........AAAAAA........
......AAAAAAAAAA......
.....AAAAAAAAAAAA.....
....AAAAAAAAAAAAAA....
....AAAAAAAAAAAAAA....
...AAAAAAAAAAAAAAAA...
...BBBBBBBBBBBBBBBB...
...BBBBBBBBBBBBBBBB...
....BBBBBBBBBBBBBB....
....BBBBBBBBBBBBBB....
.....BBBBBBBBBBBB.....
......BBBBBBBBBB......
........BBBBBB........
.........RRRR.........
........R.RR.R........
.......R..RR..R.......
......KKKKKKKKKK......
......KKKKKKKKKK......
......KKKKKKKKKK......
.......KKKKKKKK.......
""", {'A': 4, 'B': 7, 'R': 13, 'K': 15})

UMBRELLA = ("""
..........VV..........
........PPVVPP........
......PPPPVVPPPP......
.....PPPPVVVVPPPP.....
....WPPPPVVVVPPPPW....
...WWPPPPVVVVPPPPWW...
..WWWPPPPVVVVPPPPWWW..
.WWWWPPPPVVVVPPPPWWWW.
DDDDDDDDDDDDDDDDDDDDDD
..........HH..........
..........HH..........
..........HH..........
..........HH..........
..........HH..........
..........HH..........
..........HH..........
.........HHH..........
........HHH...........
........HHH...........
.........HH...........
""", {'P': 18, 'V': 25, 'W': 2, 'D': 21, 'H': 19})

ROCKET = ("""
...........NN...........
..........NNNN..........
.........NNNNNN.........
........NNNNNNNN........
........BBBBBBBB........
.......BBBBBBBBBB.......
.......BBBBBBBBBB.......
.......BBBWWWWBBB.......
.......BBBWWWWBBB.......
.......BBBWWWWBBB.......
.......BBBBBBBBBB.......
.......BBBBBBBBBB.......
......BBBBBBBBBBBB......
.....BBBBBBBBBBBBBB.....
....FBBBBBBBBBBBBBBF....
...FFBBBBBBBBBBBBBBFF...
..FFFBBBBBBBBBBBBBBFFF..
.FFFF.BBBBBBBBBBBB.FFFF.
FFFF...BBBBBBBBBB...FFFF
........EEEEEEEE........
.........EEEEEE.........
..........EEEE..........
...........EE...........
""", {'N': 0, 'B': 23, 'W': 28, 'F': 22, 'E': 4})

BUTTERFLY = ("""
........T.......T.......
.........T.....T........
..........T...T.........
...........KK...........
..OOOO.....KK.....OOOO..
.OOOOOOO...KK...OOOOOOO.
OOOOYYOOO..KK..OOOYYOOOO
OOOOYYOOOO.KK.OOOOYYOOOO
OOOOOOOOOO.KK.OOOOOOOOOO
.OOOOOOOOO.KK.OOOOOOOOO.
..OOOOOOOO.KK.OOOOOOOO..
...PPPPPPP.KK.PPPPPPP...
..PPPPPPPP.KK.PPPPPPPP..
.PPPPYYPPP.KK.PPPYYPPPP.
.PPPPYYPPP.KK.PPPYYPPPP.
..PPPPPPPP.KK.PPPPPPPP..
...PPPPPPP.KK.PPPPPPP...
....PPPPP..KK..PPPPP....
.....PPP...KK...PPP.....
...........KK...........
...........KK...........
...........KK...........
""", {'O': 30, 'P': 25, 'K': 21, 'Y': 8, 'T': 13})

DRAGON = ("""
...HH................HH...
...HHH..............HHH...
....HHH............HHH....
.....HHH..........HHH.....
......SSSSSSSSSSSSSS......
.....SSSSSSSSSSSSSSSS.....
....SSSSSSSSSSSSSSSSSS....
...SSSSSSSSSSSSSSSSSSSS...
...SSSEEESSSSSSSSEEESSS...
...SSSEEESSSSSSSSEEESSS...
...SSSSSSSSSSSSSSSSSSSS...
...SSSSSSSSSSSSSSSSSSSS...
....SSSSSNNSSSSNNSSSSS....
....SSSSSNNSSSSNNSSSSS....
....SSSSSSSSSSSSSSSSSS....
.....DDDDDDDDDDDDDDDD.....
.....DMMMMMMMMMMMMMMD.....
......DMMMMMMMMMMMMD......
......DDDDDDDDDDDDDD......
""", {'S': 31, 'H': 8, 'E': 6, 'N': 15, 'D': 0, 'M': 22})

PACK = [
    ('새싹', 'Easy', 3, SPROUT),
    ('물방울', 'Easy', 3, DROPLET),
    ('별', 'Easy', 3, STAR),
    ('사과', 'Medium', 3, APPLE),
    ('버섯', 'Medium', 3, MUSHROOM),
    ('열기구', 'Medium', 4, BALLOON),
    ('우산', 'Hard', 4, UMBRELLA),
    ('로켓', 'Hard', 4, ROCKET),
    ('나비', 'Hard', 5, BUTTERFLY),
    ('드래곤', 'Very Hard', 5, DRAGON),
]

# --------------------------------------------------------------------- build


def grid(art):
    rows = art.strip('\n').split('\n')
    w = max(len(r) for r in rows)
    rows = [r.ljust(w, '.') for r in rows]
    while rows and set(rows[0]) == {'.'}:
        rows.pop(0)
    while rows and set(rows[-1]) == {'.'}:
        rows.pop()
    keep = [c for c in range(w) if any(r[c] != '.' for r in rows)]
    return [r[keep[0]:keep[-1] + 1] for r in rows]


def peel(rows, name):
    """Peel the picture the way the game does and return the colours per pass.

    A shooter hits only the first live pixel walking in from an edge, so each
    pass strips exactly those surface pixels. If a pass removes nothing while
    pixels remain, some colour is walled in forever and the level is unwinnable.
    """
    h, w = len(rows), len(rows[0])
    live = {(x, y) for y in range(h) for x in range(w) if rows[y][x] != '.'}
    passes = []
    while live:
        surface = set()
        for x in range(w):
            for ys in (range(h), range(h - 1, -1, -1)):
                for y in ys:
                    if (x, y) in live:
                        surface.add((x, y))
                        break
        for y in range(h):
            for xs in (range(w), range(w - 1, -1, -1)):
                for x in xs:
                    if (x, y) in live:
                        surface.add((x, y))
                        break
        assert surface, '%s: %d pixels walled in' % (name, len(live))
        passes.append({rows[y][x] for x, y in surface})
        live -= surface
    return passes


def split(need):
    """One colour's pixel count -> shooter ammo values summing EXACTLY to it.

    gen_levels' splitter is greedy off 10/20/30/40 and folds the remainder into
    the last shooter, which can push it past 40. Here the count is divided into
    near-equal chunks around 21 instead, so every shooter lands in the 10..40
    band the original uses and a level carries a decision's worth of them
    rather than one fat shooter per colour.
    """
    if need <= 26:
        return [need]
    k = max(2, round(need / 21))
    base, rem = divmod(need, k)
    return [base + (1 if i < rem else 0) for i in range(k)]


def build(name, diff, nq, art, legend):
    rows = grid(art)
    h, w = len(rows), len(rows[0])
    passes = peel(rows, name)
    late = sorted(set(legend) - passes[0])

    pixels, counts = [], Counter()
    for y in range(h):
        for x in range(w):
            ch = rows[y][x]
            if ch == '.':
                continue
            # ASCII row 0 is the top; the board's y grows upward
            pixels.append({'x': x, 'y': h - 1 - y, 'material': legend[ch],
                           'areaX': 1, 'areaY': 1})
            counts[legend[ch]] += 1

    # Deal the shooters so consecutive queue heads offer different colours:
    # cycle the materials biggest first, then round-robin into the queues. A
    # player tapping heads in order always has a surface colour available.
    by_mat = {m: [{'material': m, 'ammo': a} for a in split(counts[m])]
              for m in counts}
    mats = sorted(by_mat, key=lambda m: -counts[m])
    order = []
    while any(by_mat.values()):
        for m in mats:
            if by_mat[m]:
                order.append(by_mat[m].pop(0))
    queues = [[] for _ in range(nq)]
    for i, sh in enumerate(order):
        queues[i % nq].append(dict(sh, id=i))

    # alignTolerance is 0.15 world units and a cell is physicalWidth/max(W,H);
    # keep the cell near the tolerance so every row and column stays hittable,
    # inside the 5.0..7.0 range the simulation expects.
    phys = min(7.0, max(5.0, 0.165 * max(w, h)))
    lvl = {
        'Difficulty': diff, 'HasTimeLimit': False, 'TimeLimit': 0,
        'SlotCount': 5, 'ConveyorLimit': 5,
        'QueueGroup': {'shooterQueues': [{'shooters': q} for q in queues]},
        'SurpriseShooters': {'Shooters': []}, 'ConnectedShooters': {'Connections': []},
        'Locks': {'Shooters': []}, 'ShooterPipes': {'Pipes': []},
        'Hammers': {'Shooters': []}, 'ShooterIceBlocks': {'Blocks': []},
        'ChainedShooters': {'Chains': []}, 'BullTotems': {'Totems': []},
        'MusicToyMallets': {'Mallets': []}, 'SlotCages': {'Cages': []},
        'AstronautShooters': {'Shooters': []}, 'ConveyorDoors': {'Doors': []},
        'PixelImageData': dict(EMPTY_PIC, **{
            'width': w, 'height': h,
            'physicalWidth': round(phys, 2), 'physicalHeight': round(phys, 2),
            'pixels': pixels, 'pixelHealths': [],
        }),
        'isValid': True, 'validationErrors': [],
        'picture': name, 'author': 'drawn for this build',
    }
    return lvl, len(passes), late


def main():
    os.makedirs(OUT, exist_ok=True)
    blobs, man = [], []
    for i, (name, diff, nq, (art, legend)) in enumerate(PACK, 1):
        lvl, npass, late = build(name, diff, nq, art, legend)
        pid = lvl['PixelImageData']

        need = Counter(p['material'] for p in pid['pixels'])
        sup = Counter()
        for q in lvl['QueueGroup']['shooterQueues']:
            for s in q['shooters']:
                sup[s['material']] += s['ammo']
        assert need == sup, (i, name, dict(need), dict(sup))

        raw = json.dumps(lvl, separators=(',', ':')).encode('utf-8')
        # mtime=0: gzip stamps the current time into its header by default, which
        # would make every rebuild produce a different pack and a noisy diff.
        blob = gzip.compress(raw, 9, mtime=0)
        blobs.append('gzip:' + base64.b64encode(blob).decode())
        man.append({'n': i, 'd': diff, 'slots': 5, 'lim': 5,
                    'px': len(pid['pixels']), 'name': name, 'f': {}})
        nsh = sum(len(q['shooters']) for q in lvl['QueueGroup']['shooterQueues'])
        print('%2d %-8s %-10s %2dx%-2d %4d px %d colours %2d shooters '
              '%2d peels late:%s'
              % (i, name, diff, pid['width'], pid['height'], len(pid['pixels']),
                 len(need), nsh, npass, late or '-'))

    js = ("/* The ten pictures of this build, drawn by hand as ASCII grids and\n"
          "   generated by tools/make_pack.py. Nothing here comes from another\n"
          "   game's level data. Each entry is gzipped JSON, base64'd, which\n"
          "   fetchLevel already knows how to read. */\n"
          'const PACK = ' + json.dumps(blobs) + ';\n'
          'const PACK_MAN = ' + json.dumps(man, ensure_ascii=False) + ';\n')
    path = os.path.join(OUT, 'levels.js')
    open(path, 'w', encoding='utf-8').write(js)
    print('\nwrote %s  %.1f KB' % (path, len(js.encode('utf-8')) / 1024))


if __name__ == '__main__':
    main()
