# The fifty pictures of this build, drawn by hand as ASCII grids: one character
# per source pixel, a legend mapping each character to a palette id, '.' for
# empty. Nothing here is derived from another game's level files.
#
# The grids are drawn at HALF the shipping resolution and doubled at build time
# by make_pack.scale2x (an EPX/scale2x pass, so diagonals round off instead of
# turning into stairs). That is what puts a level in the reference build's
# actual pixel band -- 32..48 cells wide, a few hundred to ~1900 pixels -- while
# keeping the source small enough to draw and diff by hand.
#
# Palette ids (index.html builds 34 hues in 97-degree steps):
#   0 Red        4 Orange      8 Light Amber  12 Lime      16 Green
#   2 Light Cyan 6 Sky        10 Blue         18 Magenta   22 Pink
#   25 Soft Indigo (the darkest)  32 Light Sky 2 (the palest)

SPROUT = ("""
...GG......GG...
..GGGG....GGGG..
.GGGGGG..GGGGGG.
..GGGGG..GGGGG..
...GGGG..GGGG...
.....GGSSGG.....
.......SS.......
.......SS.......
.......SS.......
......DDDDDD....
.....DDDDDDDD...
....DDDDDDDDDD..
.....DDDDDDDD...
......DDDDDD....
""", {'G': 12, 'S': 9, 'D': 15})

DROPLET = ("""
........WW........
.......WWWW.......
......WWWWWW......
......WWWWWW......
.....WWWWWWWW.....
....WWWWWWWWWW....
....WWWLLWWWWW....
...WWWWLLWWWWWW...
...WWWWLLWWWWWW...
..WWWWWLLWWWWWWW..
..WWWWWWWWWWWWWW..
..WWWWWWWWWWWWWW..
..MWWWWWWWWWWWWM..
..MMWWWWWWWWWWMM..
...MMMWWWWWWMMM...
....MMMMMMMMMM....
......MMMMMM......
........MM........
""", {'W': 2, 'L': 8, 'M': 6})

STAR = ("""
........YY........
........YY........
.......YYYY.......
.......YYYY.......
......YYYYYY......
OOOOOOYYYYYYOOOOOO
.OOOOYYYYYYYYOOOO.
..OOOYYYYYYYYOOO..
...YYYYYCCYYYYY...
...YYYYYCCYYYYY...
..YYYYYYYYYYYYYY..
..YYYYYYYYYYYYYY..
..YYYYYY..YYYYYY..
.YYYYY......YYYYY.
.OOOO........OOOO.
.OOO..........OOO.
..O............O..
""", {'Y': 8, 'O': 4, 'C': 23})

HEART = ("""
..RRRR....RRRR..
.RRRRRR..RRRRRR.
RRRRRRRRRRRRRRRR
RRRPPRRRRRRRRRRR
RRRPPRRRRRRRRRRR
RRRRRRRRRRRRRRRR
.RRRRRRRRRRRRRR.
.MMRRRRRRRRRRRR.
..MMRRRRRRRRRR..
...MMRRRRRRRR...
....MMRRRRRR....
.....MMRRRR.....
......MMRR......
.......MM.......
""", {'R': 0, 'P': 11, 'M': 22})

CLOUD = ("""
.......CCCCC......
.....CCCCCCCCC....
....CCCCCCCCCCC...
..CCCCCCCCCCCCCC..
.CCCCCCCCCCCCCCCC.
CCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCC
.CCCCCCCCCCCCCCCC.
..RRR..RRR..RRR...
..RRR..RRR..RRR...
...RR...RR...RR...
...BB...BB...BB...
""", {'C': 32, 'R': 17, 'B': 6})

MOON = ("""
.SS.....AAAA....
.SS...AAAAAAAA..
.....AAAAAAAAAA.
....AAACCAAAAAA.
....AAACCAAAAAA.
...AAAAAAAACCAA.
...AAAAAAAACCAA.
...AAAAAAAAAAAA.
...AAACCAAAAAAA.
...AAACCAAAAAAA.
....AAAAAAAAAA..
....AAAAAAAAAA..
.....AAAAAAAA...
......AAAAA.....
.SS.............
.SS.............
""", {'A': 8, 'C': 15, 'S': 32})

CHERRY = ("""
..........LLL...
.........LLLL...
.......GGGG.....
......GG..GG....
.....GG....GG...
....GG......GG..
...RRRR...RRRR..
..RRRRRR.RRRRRR.
..RRRRRR.RRRRRR.
.RRRRRRR.RRRRRRR
.RRRRRRR.RRRRRRR
.RRRRRRR.RRRRRRR
..RRRRRR.RRRRRR.
..RRRRRR.RRRRRR.
...RRRR...RRRR..
""", {'L': 5, 'G': 16, 'R': 0})

DUCK = ("""
.......AAAA.......
......AAAAAA......
.....AAADDAA......
.....AAADDAA......
...OOAAAAAAA......
...OOOAAAAAA......
.....AAAAAAA......
.....AAAAAAAA.....
...AAAAAAAAAAAA...
..AAAAAAAAAAAAAAA.
.AAAAAAAAAAAAAAAAA
.AAAAAAAAAAAAAAAA.
..AAAAAAAAAAAAAA..
....OOOO..OOOO....
""", {'A': 8, 'D': 25, 'O': 4})

FISH = ("""
.......FFFF.......
.....FFFFFFFF.....
...FFFFFFFFFFFF...
..FFFFFFFFFFFFFF..
..FFEEFFFFFFFFFFTT
.FFFEEFFFFFFFFFTTT
.FFFFFFFFFFFFFTTTT
.FFFFFFFFFFFFFTTTT
..FFFFFFFFFFFFFTTT
..FFFFFFFFFFFFFFTT
...FFFFFFFFFFFF...
.....FFFFFFFF.....
.......FFFF.......
""", {'F': 30, 'E': 25, 'T': 8})

TULIP = ("""
..PP......PP..
.PPPP....PPPP.
.PPPPP..PPPPP.
.PPPPPPPPPPPP.
.PPPPPPPPPPPP.
..PPPPPPPPPP..
..PPPPPPPPPP..
...PPPPPPPP...
....PPPPPP....
......SS......
......SS......
..GGG.SS......
.GGGGGSS......
.GGGGGSS......
..GGG.SSGGG...
......SSGGGGG.
......SSGGGGG.
......SS.GGG..
""", {'P': 22, 'S': 16, 'G': 5})

KEY = ("""
....AAAAAA......
...AAAAAAAA.....
..AAA....AAA....
..AA..DD..AA....
..AA..DD..AA....
..AAA....AAA....
...AAAAAAAA.....
....AASSAA......
......SS........
......SS........
......SS........
......SSSS......
......SS........
......SS........
......SSSS......
......SSS.......
""", {'A': 8, 'D': 19, 'S': 30})

CANDLE = ("""
......FF......
.....FFFF.....
.....FFFF.....
....FFFFFF....
....FFAAFF....
....FFAAFF....
.....FFFF.....
......FF......
......WW......
...WWWWWWWW...
..WWWWWWWWWW..
..WWWWWWWWWW..
..WWWWWWWWWW..
..WWWWWWWWWW..
..WWWWWWWWWW..
..WWWWWWWWWW..
..HHHHHHHHHH..
..HHHHHHHHHH..
""", {'F': 4, 'A': 8, 'W': 11, 'H': 22})

CUPCAKE = ("""
.......CC.......
......CCCC......
.....RRRRRR.....
...RRRRRRRRRR...
..RRRRRRRRRRRR..
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.WWWWWWWWWWWWWW.
.WWYYWWYYWWYYWW.
.WWWWWWWWWWWWWW.
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
...WWWWWWWWWW...
...WWWWWWWWWW...
....WWWWWWWW....
""", {'C': 0, 'R': 11, 'W': 15, 'Y': 8})

SNOWMAN = ("""
.....HHHHHH.....
.....HHHHHH.....
....SSSSSSSS....
.....WWWWWW.....
....WWWWWWWW....
....WEWWWWEW....
....WWWOWWWW....
....WWWWWWWW....
.....WWWWWW.....
...WWWWWWWWWW...
..WWWWWWWWWWWW..
..WWWWOWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWOWWWWW..
..WWWWWWWWWWWW..
...WWWWWWWWWW...
....WWWWWWWW....
""", {'H': 25, 'S': 0, 'W': 32, 'E': 10, 'O': 4})

APPLE = ("""
.........SS.........
.........SS...LLL...
.........SS.LLLLLL..
....RRRRRRRRLLLLL...
..RRRRRRRRRRRRLL....
.RRRRRRRRRRRRRRRR...
.RRRRRRRRRRRRRRRRD..
RRRRRRRRRRRRRRRRRDD.
RRRRRRRRRRRRRRRRRDD.
RRRRRRRRRRRRRRRRRDD.
RRRRRRRRRRRRRRRRRDD.
RRRRRRRRRRRRRRRRRDD.
.RRRRRRRRRRRRRRRDDD.
.RRRRRRRRRRRRRRRDD..
..RRRRRRRRRRRRRDD...
...RRRRRRRRRRRDD....
....RRRRRRRRDD......
......RRRRDD........
""", {'R': 0, 'D': 22, 'L': 16, 'S': 15})

MUSHROOM = ("""
......CCCCCCCC......
....CCCCCCCCCCCC....
...CCSSCCCCCCSSCC...
..CCCSSCCCCCCSSCCC..
..CCCCCCCSSCCCCCCC..
.CCCCCCCCSSCCCCCCCC.
.CCSSCCCCCCCCCCSSCC.
CCCSSCCCCCCCCCCSSCCC
CCCCCCCCCCCCCCCCCCCC
.TTTTTTTTTTTTTTTTTT.
....TTTTTTTTTTTT....
.....TTTTTTTTTT.....
.....TTTTTTTTTT.....
.....TTTTTTTTTT.....
.....TTTTTTTTTT.....
....TTTTTTTTTTTT....
...BBBBBBBBBBBBBB...
..BBBBBBBBBBBBBBBB..
""", {'C': 22, 'S': 8, 'T': 23, 'B': 15})

BALLOON = ("""
........AAAAAA........
......AAAAAAAAAA......
.....AAAAAAAAAAAA.....
....AAAAAAAAAAAAAA....
....AAAAAAAAAAAAAA....
...AAAAAAAAAAAAAAAA...
...BBBBBBBBBBBBBBBB...
...BBBBBBBBBBBBBBBB...
....BBBBBBBBBBBBBB....
....BBBBBBBBBBBBBB....
.....BBBBBBBBBBBB.....
......BBBBBBBBBB......
........BBBBBB........
.........RRRR.........
........R.RR.R........
.......R..RR..R.......
......KKKKKKKKKK......
......KKKKKKKKKK......
......KKKKKKKKKK......
.......KKKKKKKK.......
""", {'A': 4, 'B': 7, 'R': 13, 'K': 15})

UMBRELLA = ("""
..........VV..........
........PPVVPP........
......PPPPVVPPPP......
.....PPPPVVVVPPPP.....
....WPPPPVVVVPPPPW....
...WWPPPPVVVVPPPPWW...
..WWWPPPPVVVVPPPPWWW..
.WWWWPPPPVVVVPPPPWWWW.
DDDDDDDDDDDDDDDDDDDDDD
..........HH..........
..........HH..........
..........HH..........
..........HH..........
..........HH..........
..........HH..........
..........HH..........
.........HHH..........
........HHH...........
........HHH...........
.........HH...........
""", {'P': 18, 'V': 25, 'W': 2, 'D': 21, 'H': 19})

ROCKET = ("""
...........NN...........
..........NNNN..........
.........NNNNNN.........
........NNNNNNNN........
........BBBBBBBB........
.......BBBBBBBBBB.......
.......BBBBBBBBBB.......
.......BBBWWWWBBB.......
.......BBBWWWWBBB.......
.......BBBWWWWBBB.......
.......BBBBBBBBBB.......
.......BBBBBBBBBB.......
......BBBBBBBBBBBB......
.....BBBBBBBBBBBBBB.....
....FBBBBBBBBBBBBBBF....
...FFBBBBBBBBBBBBBBFF...
..FFFBBBBBBBBBBBBBBFFF..
.FFFF.BBBBBBBBBBBB.FFFF.
FFFF...BBBBBBBBBB...FFFF
........EEEEEEEE........
.........EEEEEE.........
..........EEEE..........
...........EE...........
""", {'N': 0, 'B': 23, 'W': 28, 'F': 22, 'E': 4})

BUTTERFLY = ("""
........T.......T.......
.........T.....T........
..........T...T.........
...........KK...........
..OOOO.....KK.....OOOO..
.OOOOOOO...KK...OOOOOOO.
OOOOYYOOO..KK..OOOYYOOOO
OOOOYYOOOO.KK.OOOOYYOOOO
OOOOOOOOOO.KK.OOOOOOOOOO
.OOOOOOOOO.KK.OOOOOOOOO.
..OOOOOOOO.KK.OOOOOOOO..
...PPPPPPP.KK.PPPPPPP...
..PPPPPPPP.KK.PPPPPPPP..
.PPPPYYPPP.KK.PPPYYPPPP.
.PPPPYYPPP.KK.PPPYYPPPP.
..PPPPPPPP.KK.PPPPPPPP..
...PPPPPPP.KK.PPPPPPP...
....PPPPP..KK..PPPPP....
.....PPP...KK...PPP.....
...........KK...........
...........KK...........
...........KK...........
""", {'O': 30, 'P': 25, 'K': 21, 'Y': 8, 'T': 13})

DRAGON = ("""
...HH................HH...
...HHH..............HHH...
....HHH............HHH....
.....HHH..........HHH.....
......SSSSSSSSSSSSSS......
.....SSSSSSSSSSSSSSSS.....
....SSSSSSSSSSSSSSSSSS....
...SSSSSSSSSSSSSSSSSSSS...
...SSSEEESSSSSSSSEEESSS...
...SSSEEESSSSSSSSEEESSS...
...SSSSSSSSSSSSSSSSSSSS...
...SSSSSSSSSSSSSSSSSSSS...
....SSSSSNNSSSSNNSSSSS....
....SSSSSNNSSSSNNSSSSS....
....SSSSSSSSSSSSSSSSSS....
.....DDDDDDDDDDDDDDDD.....
.....DMMMMMMMMMMMMMMD.....
......DMMMMMMMMMMMMD......
......DDDDDDDDDDDDDD......
""", {'S': 31, 'H': 8, 'E': 6, 'N': 15, 'D': 0, 'M': 22})

CACTUS = ("""
......FFFF........
.....FFFFFF.......
......GGGG........
......GGGG........
..GG..GGGG..GG....
.GGGG.GGGG.GGGG...
.GGGG.GGGG.GGGG...
.GGGGGGGGGGGGGG...
.GGGGGGGGGGGGGG...
.GGGGGGGGGGGGGG...
.GGGG.GGGG.GGGG...
..GG..GGGG..GG....
......GGGG........
......GGGG........
......GGGG........
......GGGG........
....SSSSSSSS......
...SSSSSSSSSS.....
..DDDDDDDDDDDD....
..DDDDDDDDDDDD....
..DDDDDDDDDDDD....
""", {'F': 18, 'G': 16, 'S': 15, 'D': 19})

PENGUIN = ("""
.......KKKK.......
.....KKKKKKKK.....
....KKKKKKKKKK....
....KKWWKKWWKK....
....KKWEKKWEKK....
....KKKKKKKKKK....
....KKKKOOKKKK....
....KKKKOOKKKK....
...KKKKKKKKKKKK...
..KKKKKKKKKKKKKK..
.KKKKWWWWWWWWKKKK.
.KKKWWWWWWWWWWKKK.
.KKKWWWWWWWWWWKKK.
.KKKWWWWWWWWWWKKK.
.KKKWWWWWWWWWWKKK.
.KKKWWWWWWWWWWKKK.
.KKKKWWWWWWWWKKKK.
..KKKWWWWWWWWKKK..
..KKKKWWWWWWKKKK..
...KKKKKKKKKKKK...
....OOOO..OOOO....
...OOOOO..OOOOO...
""", {'K': 25, 'W': 32, 'E': 10, 'O': 4})

BEE = ("""
....WWW......WWW....
...WWWWW....WWWWW...
....WWWWW..WWWWW....
......WWWWWWWW......
.......YYYYYY.......
......YYYYYYYY......
.....YYYYYYYYYY.....
....KKKKKKKKKKKK....
....YYYYYYYYYYYY....
....YYYYYYYYYYYY....
....KKKKKKKKKKKK....
....YYYYYYYYYYYY....
.....YYYYYYYYYY.....
.....KKKKKKKKKK.....
......YYEEYYYY......
......YYEEYYYY......
.......YYYYYY.......
........KKKK........
""", {'W': 32, 'Y': 8, 'K': 25, 'E': 10})

WHALE = ("""
..........SS..........
.........SSSS.........
........SS..SS........
.....BBBBBBBBBBB......
...BBBBBBBBBBBBBBB....
..BBBBBBBBBBBBBBBBB...
.BBBEEBBBBBBBBBBBBBB..
.BBBEEBBBBBBBBBBBBBBB.
BBBBBBBBBBBBBBBBBBBBB.
BWWWWWWWWWBBBBBBBBBBBB
BWWWWWWWWWWBBBBBBBBBBB
.WWWWWWWWWWWBBBBBBBBB.
.WWWWWWWWWWWBBBBBBBB..
..WWWWWWWWWWBBBBBBB...
...WWWWWWWWWWBBBB.....
.....WWWWWWWW.........
""", {'B': 10, 'W': 32, 'E': 25, 'S': 17})

LIGHTHOUSE = ("""
.......YYYY.......
......YYYYYY......
......YKKKKY......
.....RRRRRRRR.....
.....RRRRRRRR.....
....WWWWWWWWWW....
....WWWWWWWWWW....
....RRRRRRRRRR....
....RRRRRRRRRR....
....WWWWWWWWWW....
...WWWWWWWWWWWW...
...RRRRRRRRRRRR...
...RRRRRRRRRRRR...
...WWWWWWWWWWWW...
..WWWWWWWWWWWWWW..
..RRRRRRRRRRRRRR..
..RRRRRRRRRRRRRR..
..WWWWWWWWWWWWWW..
.WWWWWWWWWWWWWWWW.
.KKKKKKKKKKKKKKKK.
.KKKKKKKKKKKKKKKK.
BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB
""", {'Y': 8, 'K': 25, 'R': 0, 'W': 32, 'B': 6})

GHOST = ("""
......GGGGGG......
....GGGGGGGGGG....
...GGGGGGGGGGGG...
..GGGGGGGGGGGGGG..
..GGGGGGGGGGGGGG..
..GGKKGGGGGGKKGG..
..GGKKGGGGGGKKGG..
..GGGGGGGGGGGGGG..
..GGGGGGGGGGGGGG..
..GGGGGMMMMGGGGG..
..GGGGGMMMMGGGGG..
..GGGGGGGGGGGGGG..
..GGGGGGGGGGGGGG..
..GGGGGGGGGGGGGG..
..GGGGGGGGGGGGGG..
..GGGGGGGGGGGGGG..
..GGGGGGGGGGGGGG..
..GG..GGGG..GGGG..
..GG..GGGG..GGGG..
...B....BB....B...
""", {'G': 32, 'K': 25, 'M': 22, 'B': 14})

WATERMELON = ("""
....RRRRRRRRRRRR....
..RRRRRRRRRRRRRRRR..
.RRRRRRRRRRRRRRRRRR.
RRRRKRRRRRRRRRKRRRRR
RRRRRRRRKRRRRRRRRRRR
RRRRRRRRRRRRRRKRRRRR
.RRRKRRRRRRRRRRRRRR.
.RRRRRRRRRRKRRRRRRR.
..RRRRRRRRRRRRRRRR..
..WWWWWWWWWWWWWWWW..
...WWWWWWWWWWWWWW...
...GGGGGGGGGGGGGG...
....GGGGGGGGGGGG....
.....GGGGGGGGGG.....
......GGGGGGGG......
........GGGG........
""", {'R': 0, 'K': 25, 'W': 32, 'G': 16})

TRAIN = ("""
....KKKK..............
....KKKK..............
...RRRRRRRRRR.........
..RRRRRRRRRRRR.RRRRRR.
..RRWWRRWWRRRR.RWWWWR.
..RRWWRRWWRRRR.RWWWWR.
..RRRRRRRRRRRR.RRRRRR.
..RRRRRRRRRRRR.RRRRRR.
.KKKKKKKKKKKK.KKKKKKK.
.KKKKKKKKKKKK.KKKKKKK.
..GGG...GGG....GG.GG..
.GGGGG.GGGGG..GGGGGGG.
.GGGGG.GGGGG..GGGGGGG.
..GGG...GGG....GG.GG..
""", {'K': 25, 'R': 0, 'W': 32, 'G': 19})

CASTLE = ("""
.FF...................
.FF...................
.KKK..KKK..KKK..KKKK..
.KKK..KKK..KKK..KKKK..
.KKKKKKKKKKKKKKKKKKK..
.KKKKKKKKKKKKKKKKKKK..
.KKWWKKKKWWKKKKWWKKK..
.KKWWKKKKWWKKKKWWKKK..
.KKKKKKKKKKKKKKKKKKK..
.KKKKKKKKKKKKKKKKKKK..
.KKKKKKKKKKKKKKKKKKK..
.KKKKKKKDDDDKKKKKKKK..
.KKKKKKKDDDDKKKKKKKK..
.KKKKKKKDDDDKKKKKKKK..
.KKKKKKKDDDDKKKKKKKK..
.KKKKKKKDDDDKKKKKKKK..
GGGGGGGGGGGGGGGGGGGGGG
GGGGGGGGGGGGGGGGGGGGGG
GGGGGGGGGGGGGGGGGGGGGG
GGGGGGGGGGGGGGGGGGGGGG
""", {'F': 0, 'K': 32, 'W': 6, 'D': 19, 'G': 5})

OCTOPUS = ("""
......PPPPPPPPPP......
....PPPPPPPPPPPPPP....
...PPPPPPPPPPPPPPPP...
..PPPPPPPPPPPPPPPPPP..
..PPPWWWPPPPWWWPPPPP..
..PPPWKWPPPPWKWPPPPP..
..PPPWWWPPPPWWWPPPPP..
..PPPPPPPPPPPPPPPPPP..
..PPPPPPMMMMPPPPPPPP..
..PPPPPPPPPPPPPPPPPP..
...PPPPPPPPPPPPPPPP...
...PPPPPPPPPPPPPPPP...
..PP.PP.PP..PP.PP.PP..
.PP..PP..PP.PP..PP..PP
.PP..PP..PP.PP..PP..PP
PP...PP..PP.PP..PP...P
PP...PP..PP.PP..PP...P
.P...PP..PP.PP..PP....
.....PP..PP.PP..PP....
....PPP..PP.PP..PPP...
....PPP..PP.PP..PPP...
.....P....P..P....P...
""", {'P': 18, 'W': 32, 'K': 25, 'M': 0})

OWL = ("""
...BB............BB...
...BBB..........BBB...
....BBBBBBBBBBBBBB....
...BBBBBBBBBBBBBBBB...
..BBBBBBBBBBBBBBBBBB..
..BBWWWWWBBBBWWWWWBB..
..BBWWKWWBBBBWWKWWBB..
..BBWWWWWBBBBWWWWWBB..
..BBBBBBBOOBBBBBBBBB..
..BBBBBBBOOBBBBBBBBB..
..BBBBBBBBBBBBBBBBBB..
.BBBBCCCCCCCCCCCCBBBB.
.BBBCCCCCCCCCCCCCCBBB.
.BBBCCCCCCCCCCCCCCBBB.
.BBBCCCCCCCCCCCCCCBBB.
.BBBBCCCCCCCCCCCCBBBB.
..BBBBCCCCCCCCCCBBBB..
..BBBBBCCCCCCCCBBBBB..
...BBBBBBBBBBBBBBBB...
....BBBBBBBBBBBBBB....
.....OOOO....OOOO.....
.....OOOO....OOOO.....
""", {'B': 19, 'W': 32, 'K': 25, 'O': 4, 'C': 8})

FOX = ("""
..OO..............OO..
..OPO............OPO..
..OPPO..........OPPO..
..OPPOO........OOPPO..
..OOOOOOOOOOOOOOOOOO..
..OOOOOOOOOOOOOOOOOO..
.OOOOOOOOOOOOOOOOOOOO.
.OOOOKKOOOOOOOOKKOOOO.
.OOOOKKOOOOOOOOKKOOOO.
.OOOOOOOOOOOOOOOOOOOO.
..OOOOWWWWWWWWWWOOOO..
..OOOWWWWWWWWWWWWOOO..
..OOOWWWWWWWWWWWWOOO..
...OOWWWWKKKKWWWWOO...
...OOWWWWKKKKWWWWOO...
....OWWWWWWWWWWWWO....
.....WWWWWWWWWWWW.....
......WWWWWWWWWW......
.......WWWWWWWW.......
........WWWWWW........
""", {'O': 30, 'P': 22, 'K': 25, 'W': 32})

LION = ("""
.....MMMMMMMMMMMM.....
...MMMMMMMMMMMMMMMM...
..MMMMMMMMMMMMMMMMMM..
.MMMMMMMMMMMMMMMMMMMM.
.MMMMYYYYYYYYYYYYMMMM.
MMMMYYYYYYYYYYYYYYMMMM
MMMMYYYYYYYYYYYYYYMMMM
MMMYYYYKKYYYYKKYYYYMMM
MMMYYYYKKYYYYKKYYYYMMM
MMMYYYYYYYYYYYYYYYYMMM
MMMYYYYYYKKKKYYYYYYMMM
MMMYYYYYYKKKKYYYYYYMMM
MMMYYYYYRRRRRRYYYYYMMM
.MMMYYYYRRRRRRYYYYMMM.
.MMMMYYYYYYYYYYYYMMMM.
..MMMMYYYYYYYYYYMMMM..
...MMMMMMMMMMMMMMMM...
....MMMMMMMMMMMMMM....
.....MMMMMMMMMMMM.....
......MMMMMMMMMM......
.......MMMMMMMM.......
........MMMMMM........
""", {'M': 4, 'Y': 8, 'K': 25, 'R': 22})

ROBOT = ("""
.........AA.........
.........AA.........
........AAAA........
.....KKKKKKKKKK.....
....KKKKKKKKKKKK....
....KKCCKKKKCCKK....
....KKCCKKKKCCKK....
....KKKKKKKKKKKK....
....KKKKRRRRKKKK....
....KKKKKKKKKKKK....
.....KKKKKKKKKK.....
..GG.KKKKKKKKKK.GG..
.GGGGKKKKKKKKKKGGGG.
.GGGGKKKKKKKKKKGGGG.
.GGG.KKKKKKKKKK.GGG.
.GGG.KKCCCCCCKK.GGG.
.....KKCCCCCCKK.....
.....KKKKKKKKKK.....
.....KKKKKKKKKK.....
.....KKKK..KKKK.....
.....KKKK..KKKK.....
.....KKKK..KKKK.....
....GGGGG..GGGGG....
....GGGGG..GGGGG....
""", {'A': 8, 'K': 32, 'C': 2, 'R': 0, 'G': 25})

GUITAR = ("""
.......NNN........
.......NNN........
.......SSS........
.......NNN........
.......NNN........
.......SSS........
.......NNN........
.......NNN........
.......SSS........
.......NNN........
....OOOOOOOOO.....
...OOOOOOOOOOO....
..OOOOOOOOOOOOO...
..OOOOOOOOOOOOO...
...OOOOOOOOOOO....
...OOOOOOOOOOO....
..OOOOONNNOOOOO...
.OOOOONNNNNOOOOO..
.OOOOONNNNNOOOOO..
OOOOOOONNNOOOWWWW.
OOOOOOOOOOOWWWWWW.
OOOOOOOOOOOWWWWW..
.OOOOOOOOOOOWWW...
..OOOOOOOOOOOOO...
...OOOOOOOOOOO....
.....OOOOOOO......
""", {'N': 25, 'S': 8, 'O': 19, 'W': 0})

CAR = ("""
.......WWWWWWWWW........
......WWWWWWWWWWW.......
.....WWCCCCCCCCCWW......
....WWWCCCCCCCCCWWW.....
...RRRRRRRRRRRRRRRRR....
..RRRRRRRRRRRRRRRRRRR...
.RRRRRRRRRRRRRRRRRRRRR..
RRRRRRRRRRRRRRRRRRRRRRR.
RRRRRRRRRRRRRRRRRRRRRRR.
RRRRRRRRRRRRRRRRRRRRRRR.
.RRRRRRRRRRRRRRRRRRRRR..
..KKKKK.......KKKKK.....
.KKKKKKK.....KKKKKKK....
.KKGGGKK.....KKGGGKK....
.KKKKKKK.....KKKKKKK....
..KKKKK.......KKKKK.....
""", {'W': 32, 'C': 2, 'R': 0, 'K': 25, 'G': 8})

PIZZA = ("""
..........YY..........
.........YYYY.........
.........YYYY.........
........YYYYYY........
.......YYYYYYYY.......
.......YYRRYYYY.......
......YYYYRRYYYY......
......YYYYYYYYYY......
.....YYYYYYYYYYYY.....
.....YYRRYYYYRRYY.....
....YYYYRRYYYYRRYY....
....YYYYYYYYYYYYYY....
...YYYYYYYYYYYYYYYY...
...YYRRYYYYYYYYRRYY...
..YYYYRRYYYYYYYYRRYY..
..YYYYYYYYYYYYYYYYYY..
.YYYYYYYYYYYYYYYYYYYY.
.CCCCCCCCCCCCCCCCCCCC.
.CCCCCCCCCCCCCCCCCCCC.
.OOOOOOOOOOOOOOOOOOOO.
""", {'Y': 8, 'R': 0, 'C': 15, 'O': 19})

CROWN = ("""
..YY........YY........YY
.YYYY......YYYY......YYY
.YYYY......YYYY......YYY
YYYYYY....YYYYYY....YYYY
YYYYYY....YYYYYY....YYYY
YYYYYYY..YYYYYYYY..YYYYY
YYYYYYYYYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYYYYYYYYY
YYYRRYYYYYYBBYYYYYYGGYYY
YYYRRYYYYYYBBYYYYYYGGYYY
YYYYYYYYYYYYYYYYYYYYYYYY
YYYYYYYYYYYYYYYYYYYYYYYY
KKKKKKKKKKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKKKKKKKKKK
KKKKKKKKKKKKKKKKKKKKKKKK
.OOOOOOOOOOOOOOOOOOOOOO.
.OOOOOOOOOOOOOOOOOOOOOO.
""", {'Y': 8, 'R': 0, 'B': 10, 'G': 16, 'K': 4, 'O': 19})

CLOCK = ("""
.......BB....BB.......
.......BB....BB.......
.......KKKKKKKK.......
.....KKKKKKKKKKKK.....
...KKKKKKKKKKKKKKKK...
..KKKKWWWWWWWWWWKKKK..
..KKKWWWWWWWWWWWWKKK..
.KKKWWWWWRRWWWWWWWKKK.
.KKWWWWWWRRWWWWWWWWKK.
.KKWWWWWWRRWWWWWWWWKK.
KKKWWWWWWRRWWWWWWWWKKK
KKWWRRWWWRRWWWRRWWWWKK
KKWWWWWWWRRRRRRRRWWWKK
KKWWWWWWWWWWWWWWWWWWKK
KKWWWWWWWWWWWWWWWWWWKK
KKKWWWWWWWWWWWWWWWWKKK
.KKWWWWRRWWWWRRWWWWKK.
.KKKWWWWWWWWWWWWWWKKK.
..KKKWWWWWWWWWWWWKKK..
..KKKKWWWWWWWWWWKKKK..
...KKKKKKKKKKKKKKKK...
.....KKKKKKKKKKKK.....
.......KKKKKKKK.......
""", {'B': 8, 'K': 19, 'W': 32, 'R': 25})

SUBMARINE = ("""
...........KK...........
...........KK...........
........KKKKKKKK........
........KKKKKKKK........
.....YYYYYYYYYYYYYY.....
...YYYYYYYYYYYYYYYYYY...
..YYYYYYYYYYYYYYYYYYYY..
.YYYCCYYYCCYYYCCYYYYYYY.
.YYYCCYYYCCYYYCCYYYYYYYR
YYYYYYYYYYYYYYYYYYYYYYRR
YYYYYYYYYYYYYYYYYYYYYRRR
.YYYYYYYYYYYYYYYYYYYYYRR
.YYYYYYYYYYYYYYYYYYYYYR.
..YYYYYYYYYYYYYYYYYYYY..
...YYYYYYYYYYYYYYYYYY...
.....YYYYYYYYYYYYYY.....
........BB....BB........
........BB....BB........
""", {'K': 25, 'Y': 8, 'C': 2, 'R': 0, 'B': 17})

BRONTO = ("""
..............GGGG........
............GGGGGGGG......
...........GGGKKGGGG......
...........GGGKKGGGG......
...........GGGGGGGGG......
...........GGGGGG.........
...........GGGGG..........
...........GGGGG..........
...........GGGGG..........
.....GGGGGGGGGGG..........
...GGGSSGGGGGGGGGG........
..GGGGSSGGGGGSSGGGGG......
.GGGGGGGGGGGGSSGGGGGGG....
GGGGSSGGGGGGGGGGGSSGGGGG..
GGGGSSGGGGGGGGGGGSSGGGGGG.
.BBBBBBBBBBBBBBBBBBBBBBBBB
..BBBBBBBBBBBBBBBBBBBBBBBB
...GGGGGGGGGGGGGGGGGGGG...
....GGGG......GGGG........
....GGGG......GGGG........
....GGGG......GGGG........
....LLLL......LLLL........
""", {'G': 16, 'K': 25, 'S': 5, 'B': 8, 'L': 31})

UNICORN = ("""
..........YY............
.........YYYY...........
........WWWWWW..........
.......WWWWWWWW.........
......WWWWWWWWWW........
......WWWKKWWWWWW.......
......WWWKKWWWWWWP......
......WWWWWWWWWWPP......
.......WWWWWWWPPPP......
.......WWWWWWCCCC.......
........WWWWCCCC........
........WWWWWWW.........
.......WWWWWWWWW........
......WWWWWWWWWWWW......
.....WWWWWWWWWWWWWWW....
....WWWWWWWWWWWWWWWWW...
...WWWWWWWWWWWWWWWWWWW..
...WWWWWWWWWWWWWWWWWWW..
...WWWWWWWWWWWWWWWWWWW..
...WWWW...WWWW...WWWW...
...WWWW...WWWW...WWWW...
...WWWW...WWWW...WWWW...
...KKKK...KKKK...KKKK...
""", {'Y': 8, 'W': 32, 'K': 25, 'P': 18, 'C': 2})

PIRATE = ("""
............KK............
...........KKKK...........
..........WWWWWWWW........
.........WWWWWWWWWW.......
.........WWWKKWWWWW.......
.........WWKKKKWWWW.......
.........WWWKKWWWWW.......
.........WWWWWWWWWW.......
............KK............
.........WWWWWWWWWW.......
........WWWWWWWWWWWW......
........WWWWWWWWWWWW......
........WWWWWWWWWWWW......
............KK............
..BBBBBBBBBBBBBBBBBBBBBB..
.BBBBBBBBBBBBBBBBBBBBBBBB.
.BBYYBBYYBBYYBBYYBBYYBBBB.
.BBBBBBBBBBBBBBBBBBBBBBBB.
..BBBBBBBBBBBBBBBBBBBBBB..
...BBBBBBBBBBBBBBBBBBBB...
.....SSSSSSSSSSSSSSSS.....
.......SSSSSSSSSSSS.......
""", {'K': 25, 'W': 32, 'B': 19, 'Y': 8, 'S': 6})

TURTLE = ("""
..................GGGG....
.................GGGGGG...
.................GKKGGG...
.................GGGGGG...
..GGGG...........GGGGG....
.GGGGGG...SSSSSSSSSSSS....
.GGGGGGSSSSSSSSSSSSSSSS...
..GGGSSSSSSBBSSBBSSSSSSS..
....SSSSSBBBBSSBBBBSSSSS..
...SSSSSSBBBBSSBBBBSSSSS..
...SSSSSSSSSSSSSSSSSSSSS..
...SSSSSSBBBBSSBBBBSSSSS..
...SSSSSSBBBBSSBBBBSSSSS..
..GGGSSSSSSSSSSSSSSSSSS...
.GGGGGGSSSSSSSSSSSSSSS....
.GGGGGG...SSSSSSSSSS......
..GGGG....................
""", {'G': 16, 'K': 25, 'S': 31, 'B': 19})

CAKE = ("""
....FF....FF....FF........
....YY....YY....YY........
....YY....YY....YY........
..PPPPPPPPPPPPPPPPPP......
.PPPPPPPPPPPPPPPPPPPP.....
.WWWWWWWWWWWWWWWWWWWW.....
.WWWWWWWWWWWWWWWWWWWW.....
.WWCCWWCCWWCCWWCCWWWW.....
.WWWWWWWWWWWWWWWWWWWW.....
PPPPPPPPPPPPPPPPPPPPPP....
PPPPPPPPPPPPPPPPPPPPPP....
WWWWWWWWWWWWWWWWWWWWWW....
WWWWWWWWWWWWWWWWWWWWWW....
WWCCWWCCWWCCWWCCWWCCWW....
WWWWWWWWWWWWWWWWWWWWWW....
PPPPPPPPPPPPPPPPPPPPPPP...
PPPPPPPPPPPPPPPPPPPPPPP...
WWWWWWWWWWWWWWWWWWWWWWW...
WWWWWWWWWWWWWWWWWWWWWWW...
WWCCWWCCWWCCWWCCWWCCWWW...
WWWWWWWWWWWWWWWWWWWWWWW...
KKKKKKKKKKKKKKKKKKKKKKK...
KKKKKKKKKKKKKKKKKKKKKKK...
""", {'F': 0, 'Y': 8, 'P': 11, 'W': 15, 'C': 22, 'K': 19})

TREE = ("""
.........LLLLLL...........
.......LLLLLLLLLL.........
.....LLLLLLLLLLLLLL.......
....LLLLLLLLLLLLLLLL......
...LLLLGGLLLLLLGGLLLL.....
...LLLLLLLLLLLLLLLLLL.....
..LLLLLLLLLLLLLLLLLLLL....
..LLLLLLLLRRLLLLLLLLLL....
..LLLLLLLLLLLLLLLLLLLL....
..LLLGGLLLLLLLLLLGGLLL....
..LLLLLLLLLLLLLLLLLLLL....
...LLLLLLLLLLLLLLLLLL.....
...LLLLLLRRLLLLLLLLLL.....
....LLLLLLLLLLLLLLLL......
.....LLLLLLLLLLLLLL.......
.......LLLLLLLLLL.........
..........KKKK............
..........KKKK............
..........KKKK............
..........KKKK............
.........KKKKKK...........
.........KKKKKK...........
........KKKKKKKK..........
.......KKKKKKKKKK.........
....SSSSSSSSSSSSSSSS......
...SSSSSSSSSSSSSSSSSS.....
""", {'L': 16, 'G': 5, 'R': 0, 'K': 19, 'S': 31})

PHOENIX = ("""
..........RR..............
.........RRRR.............
........RRRRRR............
.......RRRKKRRR...........
.......RRRKKRRR...........
.......RRRRRRRR...........
MM.....RRRRRRRR.....MM....
MMRR...OOOOOOOO...RRMM....
MMRRRROOOOOOOOOORRRRMM....
.RRRRROOOOOOOOOORRRRR.....
.RRRRRYYYYYYYYYYRRRRR.....
.RRRRRYYYYYYYYYYRRRRR.....
..RRRRYYYYYYYYYYRRRR......
...RRRYYYYYYYYYYRRR.......
....RROOOOOOOOOORR........
......OOOOOOOOOO..........
......OOOOOOOOOO..........
.......YYYYYYYY...........
.......YYYYYYYY...........
......YY..YY..YY..........
.....YY...YY...YY.........
....YY....YY....YY........
....YY....YY....YY........
....RR....RR....RR........
""", {'R': 0, 'O': 4, 'Y': 8, 'K': 25, 'M': 18})

SPACESHIP = ("""
...........KK.............
..........KKKK............
.........CCCCCC...........
........CCCCCCCC..........
.......CCCCCCCCCC.........
....WWWWWWWWWWWWWWWW......
..WWWWWWWWWWWWWWWWWWWW....
.WWWWWWWWWWWWWWWWWWWWWW...
WWWWWWWWWWWWWWWWWWWWWWWW..
WWKKWWKKWWKKWWKKWWKKWWWW..
WWWWWWWWWWWWWWWWWWWWWWWW..
.WWWWWWWWWWWWWWWWWWWWWW...
..WWWWWWWWWWWWWWWWWWWW....
....WWWWWWWWWWWWWWWW......
.......RRRR..RRRR.........
.......RRRR..RRRR.........
........RR....RR..........
........YY....YY..........
........YY....YY..........
.........Y....Y...........
""", {'K': 25, 'C': 2, 'W': 32, 'R': 0, 'Y': 8})

VOLCANO = ("""
..........OO..............
.........OOOO.............
.........RRRR.............
........RRRRRR............
.......RRRRRRRR...........
......KKRRRRRRKK..........
.....KKKKRRRRKKKK.........
....KKKKKKRRKKKKKK........
...KKKKKKKKKKKKKKKK.......
..KKKKKKKKKKKKKKKKKK......
..KKKKKKKKKKKKKKKKKKK.....
.KKKKKKKKKKKKKKKKKKKKK....
.KKKKKKKKKKKKKKKKKKKKKK...
KKKKKKKKKKKKKKKKKKKKKKKK..
KKKKKKKKKKKKKKKKKKKKKKKKK.
KKKKKKKKKKKKKKKKKKKKKKKKK.
GGGGGGGGGGGGGGGGGGGGGGGGGG
GGGGGGGGGGGGGGGGGGGGGGGGGG
BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBB
""", {'O': 8, 'R': 0, 'K': 25, 'G': 31, 'B': 6})

# name, difficulty, queue count, picture
PACK = [
    ('새싹',     'Easy',      3, SPROUT),
    ('물방울',   'Easy',      3, DROPLET),
    ('별',       'Easy',      3, STAR),
    ('하트',     'Easy',      3, HEART),
    ('구름',     'Easy',      3, CLOUD),
    ('달',       'Easy',      3, MOON),
    ('체리',     'Easy',      3, CHERRY),
    ('오리',     'Easy',      3, DUCK),
    ('물고기',   'Easy',      3, FISH),
    ('튤립',     'Easy',      4, TULIP),
    ('열쇠',     'Easy',      4, KEY),
    ('양초',     'Easy',      4, CANDLE),
    ('컵케이크', 'Easy',      4, CUPCAKE),
    ('눈사람',   'Easy',      4, SNOWMAN),
    ('사과',     'Medium',    4, APPLE),
    ('버섯',     'Medium',    4, MUSHROOM),
    ('열기구',   'Medium',    4, BALLOON),
    ('우산',     'Medium',    4, UMBRELLA),
    ('선인장',   'Medium',    4, CACTUS),
    ('펭귄',     'Medium',    4, PENGUIN),
    ('꿀벌',     'Medium',    4, BEE),
    ('고래',     'Medium',    4, WHALE),
    ('등대',     'Medium',    4, LIGHTHOUSE),
    ('유령',     'Medium',    4, GHOST),
    ('수박',     'Medium',    4, WATERMELON),
    ('기차',     'Medium',    5, TRAIN),
    ('성',       'Medium',    5, CASTLE),
    ('로켓',     'Hard',      4, ROCKET),
    ('나비',     'Hard',      4, BUTTERFLY),
    ('문어',     'Hard',      4, OCTOPUS),
    ('부엉이',   'Hard',      4, OWL),
    ('여우',     'Hard',      4, FOX),
    ('사자',     'Hard',      5, LION),
    ('로봇',     'Hard',      5, ROBOT),
    ('기타',     'Hard',      5, GUITAR),
    ('자동차',   'Hard',      5, CAR),
    ('피자',     'Hard',      5, PIZZA),
    ('왕관',     'Hard',      5, CROWN),
    ('시계',     'Hard',      5, CLOCK),
    ('잠수함',   'Hard',      5, SUBMARINE),
    ('드래곤',   'Very Hard', 5, DRAGON),
    ('공룡',     'Very Hard', 5, BRONTO),
    ('유니콘',   'Very Hard', 5, UNICORN),
    ('해적선',   'Very Hard', 5, PIRATE),
    ('거북이',   'Very Hard', 5, TURTLE),
    ('케이크',   'Very Hard', 5, CAKE),
    ('큰나무',   'Very Hard', 5, TREE),
    ('불사조',   'Very Hard', 5, PHOENIX),
    ('우주선',   'Very Hard', 5, SPACESHIP),
    ('화산섬',   'Very Hard', 5, VOLCANO),
]
